# Generated by Django 2.2.3 on 2019-07-15 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chewy', '0002_historic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historic',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historic', to='chewy.Film'),
        ),
    ]
